### ISSUE TITLE
A question about ex4.15

### ISSUE THREAD

**Issue by lqid1998** [hebrewsnabla/S-O-MQC-HW#3]
Hello,

May I ask why in equation 4.6.26, this term c(1+c^2)^(-1/2)<1_i 1_i | 2_i 2_i> <α|α><β|β> disappeared?

p.s. There might be some typos in ex4.4, from the second line to the third line in equation 4.4.2, where γ*(x1',x1) should be equal to γ(x1,x1') by its definition. And in ex4.5, the second line of equation 4.4.3, 1/N before the integral seems to be missed out.

Regards,
lqid

**Comment by lqid1998** [comment]
> > For eq 4.6.26,
> > My expression is kind of misleading here. |1\bar{1}> is not a Hartree product, it's a Slater determinant. So, <1\bar{1} | 2\bar{2}> is not a 2e integral, it's an overlap between 2 determinants, although it looks like a 2e integral.
> 
> Sorry, it's my express misleading here. I know in the original form they are Slater determinants. After searching for each permutation, I got this 2-electron integral remaining, while others are zero because of spin forbidden. I tried hard to find why it does not show up in the next line but fail.
> 
> Regards,
> lqid

Ohh, I got it. It's even not a 2e integral; it is just an overlap integral. It does be zero because of orthogonality. Sorry for the stupid question.

**Comment by hebrewsnabla** [comment]
You need not to decompose the Slater determinants. The overlap between any two of them is zero, that's why we can do intermediate normalization. Proof can be found in Ex 2.5 or chap 2.4.1.

**Comment by lqid1998** [comment]
> You need not to decompose the Slater determinants. The overlap between any two of them is zero, that's why we can do intermediate normalization. Proof can be found in Ex 2.5 or chap 2.4.1.

Yea, thanks.
