### ISSUE TITLE
Could you please supply more details on the derivation of Ex 2.16 ? Especially on the second step in your derivation. Thanks.

### ISSUE THREAD

**Issue by OP-Luffy** [hebrewsnabla/S-O-MQC-HW#4]
Could you please supply more details on the derivation of Ex 2.16 ? 
Especially on the second step in your derivation. 
Thanks.

**Comment by hebrewsnabla** [comment]
Suppose t = <K^HP | H | L>, and we want to determine <(-1)^{p_n} P_n K^HP | H | L>.
My trick is to do the same permutation P_n on Slater determinant L, and it will yield a factor (-1)^{p_n}, i.e.
|L> = (-1)^{p_n} P_n |L>
thus, the product of the two (-1)^{p_n} goes to 1, and the overlap <K^HP | H | L> and <P_n K^HP | H | P_n L> should be the same (it seems there's no difference between them, in definition).
That's my personal idea. It may be wrong.

**Comment by OP-Luffy** [comment]
Very clever and interesting idea. Thanks for your quick reponse! 
I really appreicate your efforts on  making  study of MQC much, much more smooth :)
